# Documentation: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: lint_python_app
description: Lint a Python app

inputs:
  python-app-path:
    description: Python app path
    required: true
    default: .

runs:
  using: composite
  steps:
    - name: Install poetry
      shell: bash
      run: pip install poetry==1.4.0

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'

    - name: Install app dependencies
      shell: bash
      working-directory: ${{ inputs.python-app-path }}
      run: poetry install

    - name: Lint Python code
      shell: bash
      working-directory: ${{ inputs.python-app-path }}
      run: poetry run flake8 .
