apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  labels:
    app: minio
data:
  MINIO_ROOT_USER: minio
  MINIO_ROOT_PASSWORD: minio123
  MINIO_DOMAIN: localhost:9000
  MINIO_SERVER_URL: http://localhost:9000
  MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
