apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: swiss-ai-center
  POSTGRES_USER: swiss-ai-center
  POSTGRES_PASSWORD: swiss-ai-center
