apiVersion: apps/v1
kind: StatefulSet
metadata:
  # This name uniquely identifies the stateful set
  name: core-engine-backend-stateful
  labels:
    app: core-engine-backend
spec:
  serviceName: core-engine-backend
  replicas: 1
  selector:
    matchLabels:
      app: core-engine-backend
  template:
    metadata:
      labels:
        app: core-engine-backend
    spec:
      containers:
        - name: core-engine-backend
          image: ghcr.io/swiss-ai-center/core-engine-backend:latest
          # If you build the image locally, change the next line to `imagePullPolicy: Never` - there is no need to pull the image
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          env:
            - name: CHECK_SERVICES_AVAILABILITY_INTERVAL
              value: "30"
          envFrom:
            - configMapRef:
                name: core-engine-backend-config
