apiVersion: v1
kind: ConfigMap
metadata:
  name: core-engine-backend-config
  labels:
    app: core-engine-backend
data:
  HOST: http://localhost:8080
  ENVIRONMENT: development
  LOG_LEVEL: debug
  DATABASE_URL: postgresql://swiss-ai-center:swiss-ai-center@postgres-service:5432/swiss-ai-center
  DATABASE_CONNECT_ARGS: "{}"
  S3_ACCESS_KEY_ID: minio
  S3_SECRET_ACCESS_KEY: minio123
  S3_REGION: eu-central-2
  S3_HOST: http://minio-service:9000
  S3_BUCKET: core-engine
  SENTRY_DSN: ""
