apiVersion: apps/v1
kind: Deployment
metadata:
  name: glitchtip
  labels:
    app: glitchtip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glitchtip
  template:
    metadata:
      labels:
        app: glitchtip
    spec:
      containers:
        - name: web
          image: glitchtip/glitchtip
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: glitchtip-config
          volumeMounts:
            - name: uploads
              mountPath: /code/uploads
        - name: worker
          image: glitchtip/glitchtip
          command: [./bin/run-celery-with-beat.sh]
          envFrom:
            - configMapRef:
                name: glitchtip-config
          volumeMounts:
            - name: uploads
              mountPath: /code/uploads
        - name: redis
          image: redis
      initContainers:
        - name: migrate
          image: glitchtip/glitchtip
          command: [./manage.py]
          args: ["migrate"]
          envFrom:
            - configMapRef:
                name: glitchtip-config
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads-pvc

