apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glitchtip-ingress
spec:
  rules:
    - host: monitor-swiss-ai-center.kube.isc.heia-fr.ch
      http:
        paths:
          - backend:
              service:
                name: glitchtip
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - monitor-swiss-ai-center.kube.isc.heia-fr.ch
