apiVersion: v1
kind: ConfigMap
metadata:
  name: image-analyzer-config
  labels:
    app: image-analyzer
data:
  ENVIRONMENT: development
  LOG_LEVEL: debug
  ENGINE_URLS: '["http://core-engine-service:8080"]'
  SERVICE_URL: http://image-analyzer-service:8787
