# Documentation: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: test_python_app
description: Test a Python app

inputs:
  python-app-path:
    description: Python app path
    required: true
    default: .
  token:
    description: GitHub token
    required: true
    default: ""

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install app dependencies
      shell: bash
      working-directory: ${{ inputs.python-app-path }}
      run: pip3 install -r requirements.txt -r requirements-all.txt

    - name: Run Python tests
      shell: bash
      working-directory: ${{ inputs.python-app-path }}
      run: pytest

    - name: Coverage report
      uses: orgoro/coverage@v3.1
      if: github.event_name == 'pull_request'
      with:
        coverageFile: ${{ inputs.python-app-path }}/coverage.xml
        token: ${{ inputs.token }}


