apiVersion: v1
kind: Service
metadata:
  name: digit-recognition-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8484
      targetPort: 80
      protocol: TCP
  selector:
    app: digit-recognition
