"""initial schema

Revision ID: 904327f640c7
Revises:
Create Date: 2025-12-12 09:46:03.391914

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = '904327f640c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    print("Start")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelines',
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('status', sa.Enum('AVAILABLE', 'UNAVAILABLE', 'DISABLED', name='executionunitstatus'),
                              nullable=False),
                    sa.Column('data_in_fields', sa.JSON(), nullable=True),
                    sa.Column('data_out_fields', sa.JSON(), nullable=True),
                    sa.Column('tags', sa.JSON(), nullable=True),
                    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('slug')
                    )
    op.create_table('services',
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('status', sa.Enum('AVAILABLE', 'UNAVAILABLE', 'DISABLED', name='executionunitstatus'),
                              nullable=False),
                    sa.Column('data_in_fields', sa.JSON(), nullable=True),
                    sa.Column('data_out_fields', sa.JSON(), nullable=True),
                    sa.Column('tags', sa.JSON(), nullable=True),
                    sa.Column('url', sa.String(), nullable=True),
                    sa.Column('docs_url', sa.String(), nullable=True),
                    sa.Column('has_ai', sa.Boolean(), nullable=True),
                    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('slug')
                    )
    op.create_table('pipeline_steps',
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('needs', sa.JSON(), nullable=True),
                    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('inputs', sa.JSON(), nullable=True),
                    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
                    sa.Column('pipeline_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
                    sa.Column('service_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
                    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('pipeline_executions',
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('pipeline_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
                    sa.Column('current_pipeline_step_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
                    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
                    sa.Column('files', sa.JSON(), nullable=True),
                    sa.ForeignKeyConstraint(['current_pipeline_step_id'], ['pipeline_steps.id'], ),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('tasks',
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('data_in', sa.JSON(), nullable=True),
                    sa.Column('data_out', sa.JSON(), nullable=True),
                    sa.Column('status',
                              sa.Enum('PENDING', 'FETCHING', 'PROCESSING', 'SAVING', 'FINISHED', 'ERROR', 'SCHEDULED',
                                      'SKIPPED', 'ARCHIVED', 'UNAVAILABLE', name='taskstatus'), nullable=False),
                    sa.Column('service_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
                    sa.Column('pipeline_execution_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
                    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
                    sa.ForeignKeyConstraint(['pipeline_execution_id'], ['pipeline_executions.id'], ),
                    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    print("End")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('pipeline_executions')
    op.drop_table('pipeline_steps')
    op.drop_table('services')
    op.drop_table('pipelines')
    # ### end Alembic commands ###
