apiVersion: v1
kind: Service
metadata:
  name: image-convert-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8989
      targetPort: 80
      protocol: TCP
  selector:
    app: image-convert
