apiVersion: v1
kind: Service
metadata:
  name: ae-ano-detection-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8282
      targetPort: 80
      protocol: TCP
  selector:
    app: ae-ano-detection
