# Documentation: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses
name: backend-workflow
run-name: backend workflow

# Allow one concurrent deployment
concurrency:
  group: "backend"
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - prod
    paths:
      - .github/actions/build-and-push-docker-image-to-github/action.yml
      - .github/actions/execute-command-on-kubernetes-cluster/action.yml
      - .github/actions/lint-python-app/action.yml
      - .github/actions/test-python-app/action.yml
      - .github/workflows/backend.yml
      - backend/**/*

  pull_request:
    paths:
      - .github/actions/build-and-push-docker-image-to-github/action.yml
      - .github/actions/execute-command-on-kubernetes-cluster/action.yml
      - .github/actions/lint-python-app/action.yml
      - .github/actions/test-python-app/action.yml
      - .github/workflows/backend.yml
      - backend/**/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Lint Python app
        uses: ./.github/actions/lint-python-app
        with:
          python-app-path: ./backend

  test:
    needs: review
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Test Python app
        uses: ./.github/actions/test-python-app
        with:
          python-app-path: ./backend
          token: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: test
    runs-on: ubuntu-latest
    # Only run on main
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build and push Docker image to GitHub
        id: build-and-push-docker-image-to-github
        uses: ./.github/actions/build-and-push-docker-image-to-github
        with:
          docker-registry-username: ${{ github.actor }}
          docker-registry-password: ${{ secrets.GITHUB_TOKEN }}
          docker-image-name: swiss-ai-center/backend
          docker-image-context: ./backend
    outputs:
      docker-image-tags: ${{ steps.build-and-push-docker-image-to-github.outputs.docker-image-tags }}

  deploy:
    needs: release
    runs-on: ubuntu-latest
    # Only run on main
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Prepare configuration files
        shell: bash
        working-directory: backend/kubernetes
        env:
          HOST: https://backend-core-engine-swiss-ai-center.kube.isc.heia-fr.ch
          ENVIRONMENT: production
          LOG_LEVEL: info
          DATABASE_URL: ${{ secrets.ENGINE_DEV_DATABASE_URL }}
          DATABASE_CONNECT_ARGS: '"{}"'
          S3_ACCESS_KEY_ID: ${{ secrets.ENGINE_DEV_S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.ENGINE_DEV_S3_SECRET_ACCESS_KEY }}
          S3_HOST: ${{ secrets.ENGINE_DEV_S3_HOST }}
          S3_REGION: eu-central-2
          S3_BUCKET: engine
          SENTRY_DSN: ${{ secrets.GLITCHTIP_SENTRY_DSN }}
        run: |
          # Set Backend version
          docker_image_tags=(${{ needs.release.outputs.docker-image-tags }})
          docker_image_sha_tag="${docker_image_tags[1]}"
          yq ".spec.template.spec.containers[0].image = \"$docker_image_sha_tag\"" backend.stateful.yml > new-backend.stateful.yml && mv new-backend.stateful.yml backend.stateful.yml

          # Set Backend configuration (ConfigMap)
          yq '.data = (.data | to_entries | map({"key": .key, "value": "${" + .key + "}"}) | from_entries)' backend.config-map.yml | envsubst > new-backend.config-map.yml && mv new-backend.config-map.yml backend.config-map.yml

          # Set Backend configuration (Ingress)
          yq ".spec.rules[0].host = \"${HOST#*://}\"" backend.ingress.yml > new-backend.ingress.yml && mv new-backend.ingress.yml backend.ingress.yml
          yq ".spec.tls[0].hosts[0] = \"${HOST#*://}\"" backend.ingress.yml > new-backend.ingress.yml && mv new-backend.ingress.yml backend.ingress.yml

      - name: Deploy Backend on the Kubernetes cluster
        uses: ./.github/actions/execute-command-on-kubernetes-cluster
        with:
          kube-config: ${{ secrets.KUBE_CONFIG_DEV }}
          kube-namespace: swiss-ai-center-dev
          kubectl-context: ./backend/kubernetes
          kubectl-args: |
            apply \
              -f backend.config-map.yml \
              -f backend.stateful.yml \
              -f backend.service.yml \
              -f backend.ingress.yml
